[[colormap]]
name = "%skintones.red"
label = " - Red"
shortcode = "_r"
description = " (red variant)"
codepoint = "U+1F7E5" # red square
"$base.1" = "#cc3030"
"$base.2" = "#aa3030"
"$base.3" = "#993030"

[[colormap]]
name = "%skintones.green"
label = " - Green"
shortcode = "_g"
description = " (green variant)"
codepoint = "U+1F7E2" # green square
"$base.1" = "#30cc30"
"$base.2" = "#30aa30"
"$base.3" = "#309930"

[[define]]
"$skintones.extra" = "%skintones.red %skintones.green"

[[colormap]]
name = "%skintones.default"
label = ""
shortcode = ""
description = ""
"$base.1" = "#f1c731"
"$base.2" = "#a88b22"
"$base.3" = "#705d17"

[[emoji]]
src = "./back_of_hand [paw].svg"
name = "Back of hand (paw)%label"
category = [ "expressions", "skintones", "paw" ]
description = "something"
tags = [ "extra" ]
shortcodes = [ "back_of_hand_paw%shortcode" ]
colormaps = [ "$skintones.extra", "%skintones.default" ]

[[emoji]]
src = "./v [hmn].svg"
name = "Victory hand (human)%label"
category = [ "expressions", "skintones", "human" ]
description = "something"
tags = [ "extra" ]
shortcodes = [ "victory_hand%shortcode", "v%shortcode" ]
codepoint = [ "U+270C", "$zwj", "%codepoint" ]
colormaps = [ "$skintones.extra" ]

[[emoji]]
src = "./v [hmn].svg"
name = "Victory hand (human)"
category = [ "expressions", "skintones", "human" ]
description = "something"
tags = [ "unicode" ]
codepoint = [ "U+270C", "$vs16" ]
shortcodes = [ "victory_hand", "v" ]
colormaps = [ "%skintones.default" ]
